#!/usr/bin/env python
# coding: utf-8

# In[22]:


# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns #data visualization libraray
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
import matplotlib.pyplot as plt#for visualization graph 
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session


# In[23]:


dataframe = pd.read_csv("../input/bitcoin-historical-data/bitstampUSD_1-min_data_2012-01-01_to_2020-09-14.csv")
#Read the data frame


# In[24]:


dataframe.head() 
#This head function is used for the demonstration of 5 top data
dataframe.head(10)#10 top data is coming from the dataset file


# In[25]:


dataframe.info() #The colon and their type information will be coming


# In[26]:


dataframe.corr()


# In[28]:


#correlation map 
f,ax = plt.subplots(figsize=(20,20))
sns.heatmap(dataframe.corr(),annot=True,linewidths=.5,fmt='.1f',ax=ax)
plt.show()


# > Correlation map shows us to understand the dependency of each data.Because they can be directly or inversely proportional to each other.When visualizing the dataset helps us to understand the contrast and relationship between the each data group.

# In[30]:


dataframe.head(10)


# In[45]:


dataframe.columns


# > The columns of my dataset has been showed by the help of dataframe.columns code.

# **Visualizing the dataset by Matplotlib functions**

# In[57]:


dataframe.Low.plot(kind = 'line', color = 'black',label = 'Low',linewidth=1,alpha = 0.5,grid = True,linestyle = ':')
dataframe.Close.plot(color="purple",label="Close",linewidth=1,grid=True,linestyle="-.")
plt.legend(loc="upper right")
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
#plt.zlabel("Z-Axis")
plt.title("Bitcoin Line Plot")
plt.show()


# In[58]:


dataframe.plot(kind="scatter",x="High",y="Close",alpha=0.7,color="green")
plt.xlabel("High")
plt.ylabel("Close")
plt.title("Bitcoin High and Close Fluctiation Plot")


# In[59]:


dataframe.Low.plot(kind="hist",bins=60,figsize=(20,20))
plt.show()


# In[60]:


dataframe.High.plot(kind="hist",bins=60,figsize=(20,20))
plt.show()


# In[63]:


dataframe.Close.plot(kind="hist",bins=40)
plt.clf()


# In[65]:


data =pd.read_csv("../input/bitcoin-historical-data/bitstampUSD_1-min_data_2012-01-01_to_2020-09-14.csv")


# In[68]:


series = data['Low']
print(type(series))
data_frame = data[["Close"]]
print(type(data_frame))


# > The data frame should be filtered by giving any conditions to come true the results

# In[69]:


x = data['Close'] >5


# In[70]:


data[x]


# In[71]:


data[np.logical_and(data["Close"]>20,data["High"]>130)]


# In[72]:


data[(data["Low"]>1200) & (data["High"]>130)]


# **The whole operations are for reading,making correlation and giving some graphic visualization to demonstrate and mining the dataset as well.**
